version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # UI Admin
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest